## Chapter 5

# Theory

1. Vad menas med curse of dimensionality.

That as the dimensions of the data increases, the data becomes more unpredictable. In effect this means that it becomes harder to make predictions about it, and that it requires more datapoints to learn general patterns in the data.

2. Vad är dimensionsreducering och varför görs det?

Dimension reduction is to reduce a dataset to a lower dimension, meaning to map a higher number of variables to a lower number of variables.
This can be done for multiple reasons, such as wanting to visualize it or to reduce the time it takes to train the model, and, more importantly, it is also in some cases done to improve the prediction of patterns within the data, as this is effectively also a way to reduce the variance, but increasing the bias, preventing overfitting by throwing away outliers.

3. Förklara översiktligt hur PCA fungerar. Använd figur 5.4 på sidan 224 i din förklaring.

Principal component analysis, as the name implies, is a way of mapping the primary components of the data, reducing a higher dimensional dataset to its principal components. Figure 5.4 shows how the PCA determines these principal components in practice, first determining the axis within the high dimensional dataset which retains the most variance C1 (Typically not aligned with any existing axis corresponding with the dataset). It then selects an axis which is ortogonal to the first line as its next principal component C2. This continues until the principal component for as many dimensions the dataset contains. How many principal components are kept is then determined either as a perentage of how much variance should be maintained, or a fixed number of dimensions. We see the result of the dimensional reduction for each of the cross-axes through the leftmost 2 dimensional data, to a 1 dimensional representation on the right.

4. Hur kan kernel PCA utvärderas?

Kernel PCA is a PCA using the same kernel tricks which allows us to use some other linear techniques to classify polynomial data, to perform a non-linear projection of the data. To evaluate a kernel PCA the same methods we have encountered before, using a grid search to evaluate which kernels are best, providing the grid search function an excecution pipeline including both the kernel pca object, and an evaluation model, such that the model can be evaluated during the gridsearch.

5. Stina påstår att man i maskininlärning alltid vill ha modeller som genomför
så bra prediktioner som möjligt. Kalle påstår att det inte riktigt stämmer
eftersom tid också är en viktig aspekt. Både för själva modellträningen
och för själva prediktionerna. Vad säger du?

While optimally we would want to always have the best model, in a real world scenario, there are other factors, such as time, which also play an important role in deciding how a model is trained and constructed, say for example if the model being trained is to be deployed for a time sensitive purpose, taking excessive time to train it, would may then result in it being obsolete by the time training is finished. It is exactly this that PCA can be of help in, reducing the dimensionality, and therefore also the time it takes for models to train and evaluate the data. Given that the predictions remain sufficient for its intended purpose, the reduction in accuracy may then be a worthwhile sacrifice.

6. Efter att vi genomfört en PCA, vad händer med tolkningen av variablerna?

Since the principal components are a combination of multiple predictor variables the interpretability of the variables themselves innevitably gets reduced, as they are no longer dirrectly linked to just a single variable.

# Code

7. Gå igenom samtliga kodexempel i kapitlet och skriv gärna av koden manuellt. Det är även bra att experimentera genom att ändra vissa delar av
koden och läsa dokumentationen.

[Salute]

8. Förklara vad nedanstående kod gör.

In [ ]:
#import numpy as np
#from sklearn.decomposition import PCA
## Creating a dataset with 3 features/columns
#X = np.random.rand(1000, 3)
#print(X[0:5])
## Reducing the data to 2 dimensions
#pca = PCA(n_components=2)
#X2D = pca.fit_transform(X)
#print(X2D[0:5])
## "Recreating" the data to 3 dimensions
#X3D_inv = pca.inverse_transform(X2D)
## Not exactly equal since some information was lost in the transformation
#print(np.allclose(X3D_inv, X))

[[0.6565224  0.88799418 0.19512731]
 [0.6320696  0.45035556 0.81091713]
 [0.89695275 0.55652544 0.4895939 ]
 [0.76206111 0.36800884 0.29902456]
 [0.92739308 0.93947214 0.36827535]]
[[ 0.05274139  0.49395929]
 [-0.07895776 -0.11551923]
 [ 0.21150531  0.19694807]
 [ 0.33867646  0.05763792]
 [ 0.09345168  0.57688825]]
False


We create a random dataset with 3 components, then carry out a PCA dimension reduction to 2 dimensions as specified by the n_components. a standard scaler is then fit to the principal components, which are also transformed with the scaler, using the same function. We also print the 5 first values of each dataset to show this transformation.
After this we carry out an inverse transformation, transforming the dataset back to 3 dimensions.
Using np.allclose we then compare the inverse transformed data to the original data, which tells us that the newly transformed data does not match up with the original data before the transformation, which, as the comment states, is because of data being lost in the transformation.

9. Genomför en PCA på “car_price_dataset.csv” från kapitel 3 innan du
modellerar det med ML. Hur påverkas resultatet?